In [1]:
import os
cache_dir = "/scratches/dialfs/alta/hln35/.cache"
os.environ['TRANSFORMERS_CACHE'] = '/scratches/dialfs/alta/hln35/.cache'

In [2]:
model_small = "google/flan-t5-small"

In [3]:
from datasets import load_dataset

data_points = load_dataset("boolq", split='validation', cache_dir=cache_dir)

In [4]:
data_points

Dataset({
    features: ['question', 'answer', 'passage'],
    num_rows: 3270
})

In [5]:
data_points[0]

{'question': 'does ethanol take more energy make that produces',
 'answer': False,
 'passage': "All biomass goes through at least some of these steps: it needs to be grown, collected, dried, fermented, distilled, and burned. All of these steps require resources and an infrastructure. The total amount of energy input into the process compared to the energy released by burning the resulting ethanol fuel is known as the energy balance (or ``energy returned on energy invested''). Figures compiled in a 2007 report by National Geographic Magazine point to modest results for corn ethanol produced in the US: one unit of fossil-fuel energy is required to create 1.3 energy units from the resulting ethanol. The energy balance for sugarcane ethanol produced in Brazil is more favorable, with one unit of fossil-fuel energy required to create 8 from the ethanol. Energy balance estimates are not easily produced, thus numerous such reports have been generated that are contradictory. For instance, a sep

In [6]:
prefix = "rule: for each question there is a passage in context. answer the question by saying the statement is True or False. "


In [7]:
max_input_length = 1024

In [8]:
from transformers import AutoTokenizer
import torch
from transformers import AutoModelForQuestionAnswering, AutoModel, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained(model_small)
model = AutoModelForSeq2SeqLM.from_pretrained(model_small)
model1 = AutoModel.from_pretrained(model_small)
model2 = AutoModelForQuestionAnswering.from_pretrained(model_small)



Some weights of T5ForQuestionAnswering were not initialized from the model checkpoint at google/flan-t5-small and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [9]:
model


T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              (wo): 

In [10]:
model1

T5Model(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              (wo): Linear(in_features=

In [11]:
model2

T5ForQuestionAnswering(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              (wo): Line

In [12]:
model.config

T5Config {
  "_name_or_path": "google/flan-t5-small",
  "architectures": [
    "T5ForConditionalGeneration"
  ],
  "classifier_dropout": 0.0,
  "d_ff": 1024,
  "d_kv": 64,
  "d_model": 512,
  "decoder_start_token_id": 0,
  "dense_act_fn": "gelu_new",
  "dropout_rate": 0.1,
  "eos_token_id": 1,
  "feed_forward_proj": "gated-gelu",
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "is_gated_act": true,
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "n_positions": 512,
  "num_decoder_layers": 8,
  "num_heads": 6,
  "num_layers": 8,
  "output_past": true,
  "pad_token_id": 0,
  "relative_attention_max_distance": 128,
  "relative_attention_num_buckets": 32,
  "task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 200,
      "min_length": 30,
      "no_repeat_ngram_size": 3,
      "num_beams": 4,
      "prefix": "summarize: "
    },
    "translation_en_to_de": {
      "early_stopping": true,
      "ma

In [13]:
import json, re

In [14]:
def shift_right(input_ids, config):
        decoder_start_token_id = config.decoder_start_token_id
        pad_token_id = config.pad_token_id

        if decoder_start_token_id is None:
            raise ValueError(
                "self.model.config.decoder_start_token_id has to be defined. In T5 it is usually set to the pad_token_id."
                "See T5 docs for more information."
            )

        # shift inputs to the right
       
        shifted_input_ids = input_ids.new_zeros(input_ids.shape)
        shifted_input_ids[..., 1:] = input_ids[..., :-1].clone()
        shifted_input_ids[..., 0] = decoder_start_token_id

        if pad_token_id is None:
            raise ValueError("self.model.config.pad_token_id has to be defined.")
        # replace possible -100 values in labels by `pad_token_id`
        shifted_input_ids.masked_fill_(shifted_input_ids == -100, pad_token_id)

        return shifted_input_ids

In [17]:
question = data_points[0]["question"]
passage = data_points[0]["passage"]
ans = ""
text = prefix + "context: " + passage + ". question: " + question
ref = str(data_points[0]["answer"])
inputs = tokenizer(text, max_length=max_input_length, truncation=True, return_tensors="pt").input_ids
preds_tokenized = model(inputs, decoder_input_ids=torch.tensor([[model.config.decoder_start_token_id, model.config.decoder_start_token_id]])) 

In [19]:
inputs.shape

torch.Size([1, 323])

In [18]:
preds_tokenized

Seq2SeqLMOutput(loss=None, logits=tensor([[[-53.1579,  -5.9468, -12.0900,  ..., -53.2189, -53.1536, -53.2408],
         [-53.1579,  -5.9468, -12.0900,  ..., -53.2189, -53.1536, -53.2407]]],
       grad_fn=<UnsafeViewBackward0>), past_key_values=((tensor([[[[-0.3246, -0.4472,  2.7203,  0.5027, -1.2017, -0.0500, -0.2239,
           -0.8631,  0.4351, -1.9833, -0.0921,  0.9110,  2.4308,  0.5330,
            0.5235,  0.8297, -0.4288, -0.5965, -0.4551,  0.9857,  0.2452,
            0.8802,  1.4902,  0.2550,  1.1417,  0.5892,  0.5407,  0.1096,
            0.3798,  0.9067,  0.8513, -3.0221, -0.2641, -0.1702, -0.6509,
           -0.6096, -2.6451,  1.2174, -0.4624,  0.8654, -0.4411, -0.5461,
           -0.3555,  0.3705, -0.3718,  0.8499, -1.7910,  0.4685,  0.0680,
            0.1161, -0.0328,  0.2432,  1.0836, -0.3219,  0.6269, -0.0300,
           -0.3030,  0.5362,  0.3154, -0.2068,  0.6602,  0.5856, -0.2654,
            0.3955],
          [-0.3246, -0.4472,  2.7203,  0.5027, -1.2017, -0.0500, -

In [20]:
print(preds_tokenized.logits.shape)

torch.Size([1, 2, 32128])


In [27]:
preds_softmax = torch.nn.functional.softmax(preds_tokenized.logits, dim=-1)
preds_softmax.shape

torch.Size([1, 2, 32128])

In [23]:
tokenizer(['This sentence is False'])

{'input_ids': [[100, 7142, 19, 10747, 7, 15, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1]]}

In [24]:
tokenizer(['This sentence is True'])


{'input_ids': [[100, 7142, 19, 10998, 1]], 'attention_mask': [[1, 1, 1, 1, 1]]}

In [41]:
tokenizer.decode([10747, 7, 15])

'False'

In [28]:
preds_softmax[...,10747]

tensor([[0.6215, 0.6215]], grad_fn=<SelectBackward0>)

In [29]:
preds_softmax[...,10998]

tensor([[0.3768, 0.3768]], grad_fn=<SelectBackward0>)

In [21]:
preds_softmax.shape

torch.Size([1, 1])

In [22]:
preds_generate_tokenized = model.generate(inputs, max_new_tokens=1024, do_sample=False) 

In [23]:
preds_generate_tokenized

tensor([[    0, 10747,     7,    15,     1]])

In [24]:
ans = tokenizer.batch_decode(preds_generate_tokenized)
ans

['<pad> False</s>']

In [25]:
# for i in range(len(data_points)):
correct = 0
empty = 0
pattern = r'<pad>\s+(.*?)</s>'  

for i in range(len(data_points)):
    question = data_points[i]["question"]
    passage = data_points[i]["passage"]
    ans = ""
    text = prefix + "context: " + passage + ". question: " + question
    ref = str(data_points[i]["answer"])
    inputs = tokenizer(text, max_length=max_input_length, truncation=True, return_tensors="pt").input_ids
    preds_tokenized = model.generate(inputs, max_new_tokens=128, do_sample=False) 
    preds = tokenizer.batch_decode(preds_tokenized)

    match = re.search(pattern, preds[0]) 

    if match:
        ans = match.group(1)
    
    if ans == ref:
        correct += 1
    elif ans == "":
        empty += 1
    # print(text)
    # print(preds)
    # print(ans)
    # print(ref)
# import json
# with open("translate_bleu_small.txt", "w") as fp:
#     json.dump(scores, fp)
# print(sum(scores)/len(data_points))

KeyboardInterrupt: 

In [ ]:
print(f"Total points are {len(data_points)}. Number of correct answers is {correct}. Number of empty answers is {empty}")

In [ ]:
model_large = "google/flan-t5-large"
tokenizer_large = AutoTokenizer.from_pretrained(model_large)
model_large = AutoModelForSeq2SeqLM.from_pretrained(model_large)

In [ ]:
correct = 0
empty = 0
pattern = r'<pad>\s+(.*?)</s>'  

for i in range(len(data_points)):
    question = data_points[i]["question"]
    passage = data_points[i]["passage"]
    ans = ""
    text = prefix + "context: " + passage + ". question: " + question
    ref = str(data_points[i]["answer"])
    inputs = tokenizer_large(text,max_length=max_input_length, truncation=True, return_tensors="pt").input_ids
    preds_tokenized = model_large.generate(inputs, max_new_tokens=128, do_sample=False) 
    preds = tokenizer_large.batch_decode(preds_tokenized)

    match = re.search(pattern, preds[0]) 

    if match:
        ans = match.group(1)
    
        
    if ans == ref:
        correct += 1
    elif ans == "":
        empty += 1

In [ ]:
print(f"Total points are {len(data_points)}. Number of correct answers is {correct}. Number of empty answers is {empty}")